// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: casts_service_v1.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CastsServiceV1Client is the client API for CastsServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CastsServiceV1Client interface {
	// Returns cast with specified id.
	GetCast(ctx context.Context, in *GetCastRequest, opts ...grpc.CallOption) (*Cast, error)
	// Returns all professions.
	GetProfessions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Professions, error)
}

type castsServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewCastsServiceV1Client(cc grpc.ClientConnInterface) CastsServiceV1Client {
	return &castsServiceV1Client{cc}
}

func (c *castsServiceV1Client) GetCast(ctx context.Context, in *GetCastRequest, opts ...grpc.CallOption) (*Cast, error) {
	out := new(Cast)
	err := c.cc.Invoke(ctx, "/casts_service.castsServiceV1/GetCast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *castsServiceV1Client) GetProfessions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Professions, error) {
	out := new(Professions)
	err := c.cc.Invoke(ctx, "/casts_service.castsServiceV1/GetProfessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CastsServiceV1Server is the server API for CastsServiceV1 service.
// All implementations must embed UnimplementedCastsServiceV1Server
// for forward compatibility
type CastsServiceV1Server interface {
	// Returns cast with specified id.
	GetCast(context.Context, *GetCastRequest) (*Cast, error)
	// Returns all professions.
	GetProfessions(context.Context, *emptypb.Empty) (*Professions, error)
	mustEmbedUnimplementedCastsServiceV1Server()
}

// UnimplementedCastsServiceV1Server must be embedded to have forward compatible implementations.
type UnimplementedCastsServiceV1Server struct {
}

func (UnimplementedCastsServiceV1Server) GetCast(context.Context, *GetCastRequest) (*Cast, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCast not implemented")
}
func (UnimplementedCastsServiceV1Server) GetProfessions(context.Context, *emptypb.Empty) (*Professions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfessions not implemented")
}
func (UnimplementedCastsServiceV1Server) mustEmbedUnimplementedCastsServiceV1Server() {}

// UnsafeCastsServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CastsServiceV1Server will
// result in compilation errors.
type UnsafeCastsServiceV1Server interface {
	mustEmbedUnimplementedCastsServiceV1Server()
}

func RegisterCastsServiceV1Server(s grpc.ServiceRegistrar, srv CastsServiceV1Server) {
	s.RegisterService(&CastsServiceV1_ServiceDesc, srv)
}

func _CastsServiceV1_GetCast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CastsServiceV1Server).GetCast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/casts_service.castsServiceV1/GetCast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CastsServiceV1Server).GetCast(ctx, req.(*GetCastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CastsServiceV1_GetProfessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CastsServiceV1Server).GetProfessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/casts_service.castsServiceV1/GetProfessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CastsServiceV1Server).GetProfessions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CastsServiceV1_ServiceDesc is the grpc.ServiceDesc for CastsServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CastsServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "casts_service.castsServiceV1",
	HandlerType: (*CastsServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCast",
			Handler:    _CastsServiceV1_GetCast_Handler,
		},
		{
			MethodName: "GetProfessions",
			Handler:    _CastsServiceV1_GetProfessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "casts_service_v1.proto",
}
